Update buildtoserver.yml

diff --git a/.github/workflows/buildtoserver.yml b/.github/workflows/buildtoserver.yml
--- a/.github/workflows/buildtoserver.yml
+++ b/.github/workflows/buildtoserver.yml
@@ -37,7 +37,15 @@ jobs:
           export EXILED_REFERENCES=${{ env.EXILED_REFERENCES }}
           export EXILED_DEV_REFERENCES=${{ env.EXILED_DEV_REFERENCES }}
           SLN=$(find . -name "*.sln" | head -n 1)
-          msbuild KruacentExiled/KruacentExiled.sln \
-          /p:Configuration=Release \
-          /p:OutputPath=${{ env.OUTPUT_FOLDER_PATH }}
+          msbuild "$SLN" /p:Configuration=Release
+
+      - name: Copy plugin to server
+        run: |
+          DLL=$(find . -path "*/bin/Release/*KruacentExiled.dll" | head -n 1)
+      
+          if [ -z "$DLL" ]; then
+            echo "DLL not found!"
+            exit 1
+          fi
+          cp "$DLL" $OUTPUT_FOLDER_PATH/
 
